### ISSUE TITLE
Documentation - provide some 'why'

### ISSUE THREAD

**Issue by andybak** [karanlyons/django-save-the-change#12]
Is the main reason efficiency or does this facilitate some other advantages? I've got a few thoughts of my own but it would be great to have a few paragraphs in the readme setting out your original motivation.

**Comment by karanlyons** [comment]
The reasoning is, I’d hope, implied in [the differences in the generated SQL](https://django-save-the-change.readthedocs.org/en/latest/#save-the-change), and also [the explanation of how it works](https://django-save-the-change.readthedocs.org/en/latest/#how-it-works). The codebase is also only ~300 lines, and I’ve done my best to make it easily digestible.

Basically, you’re trading some CPU time and memory for less I/O between your application and your database (and consequently, less CPU time and memory consumed by it).

Whether that’s a tradeoff you *want* to make is up to you and based entirely on your project’s needs. STC is designed so that you can drop it in and not have to think about it, but first you’ve got to think about whether dropping it in is a good idea in the first place.

**Comment by andybak** [comment]
Sure. Maybe your answer could be summarised as "performance - but don't ignore the tradeoffs".

I was just curious about any non-performance related advantages. I've got an application where concurrent usage and locking issues is a real concern and I was curious if there was an advantage to using STC here. However I've realised that if STC is truly a transparent drop-in replacement - then that is almost a guarantee that there aren't any functional differences - beyond the performance profile.

Our of curiosity - have you done any benchmarks on your own apps?

**Comment by karanlyons** [comment]
There aren’t going to be any real non-performance advantages. The [`TrackChanges` mixin](https://django-save-the-change.readthedocs.org/en/latest/#save_the_change.mixins.TrackChanges) proves very useful in some cases, but I tend to use that for performance reasons as well (avoiding work when it’s unneeded in `Model.save()`s, for example).

There *shouldn’t* be any differences in usage of your models with or without the `SaveTheChange` mixin (which basically just automagically generates an `update_fields` for you if one isn’t supplied). `UpdateTogetherModel` *does* add some [extra functionality](https://django-save-the-change.readthedocs.org/en/latest/#save_the_change.mixins.UpdateTogetherModel), but that functionality is only concerned with STC.

For the project I built STC for there were some pretty great improvements. It’s got fairly fat models and wide tables by necessity, but the vast majority of the time we’re updating somewhere between zero and a couple fields over a large number of objects. You can obviously use `only()`/`defer()` (you still should even if using STC, since it can’t predict the future), write raw SQL for bulk upserts (much easier now that postgres has that builtin), and/or write out your own `update_fields` kwargs, and then you really wouldn’t need STC (and it’d also be faster since everything’s static; I do still do this in I/O critical sections). But CPU and memory is cheap, and I/O and an engineer’s time are not, so I saw much better performance (both for computers and humans) by just adding STC into any large model. I also *love* the `TrackChanges` mixin.

By reducing I/O to your database you reduce the amount of time it has to spend planning its query *and/or* executing it, depending on how clever your database is. I’m pretty sure postgres at least doesn’t (I mean, how could it?) excise unchanged fields from an `UPDATE` statement. This is going to translate to less time spent with your db’s rows/tables locked per `save()`, but again you aren’t getting that for free, just for cheap.
