### ISSUE TITLE
Django datetime fields with (auto_now=True) don't get updated 

### ISSUE THREAD

**Issue by binit-singh** [karanlyons/django-save-the-change#17]
DemoTable(SaveTheChange, models.Model):
  demo_name = models.CharField(max_length=50)
  modified_at = models.DateTimeField(auto_now=True)

demo_obj = DemoTable.objects.get(id=1)
demo_obj.demo_name = 'abc'
demo_obj.save()

It does not updates modified_at field.

**Comment by karanlyons** [comment]
`auto_now` and `auto_now_add` are handled by date/time fields’ [`pre_save()` method](https://github.com/django/django/blob/004ba0f99eb25c3f32aa3a41707534e955d1878e/django/db/models/fields/__init__.py#L1298-L1304). Since this is called at the end of a model’s `save()` method (specifically it’s not handled until [the underlying sql query is built](https://github.com/django/django/blob/ee596888e1149864e7828f5cf63c0eda395744c3/django/db/models/sql/compiler.py#L1005), there’s really no way at all (at least that I can currently think of) to properly handle this behavior with any sort of mixin.

It’s for reasons like this that those parameters are actually deprecated, as is the use of `pre_save()` for anything more than just data transformations.
