### ISSUE TITLE
ValueError: The following fields do not exist in this model or are m2m fields: id

### ISSUE THREAD

**Issue by bforchhammer** [karanlyons/django-save-the-change#7]
We have a problem with saving the same object repeatedly, using a post save connector. Our model looks like the following:

```
Video(SaveTheChange, BaseModel):
    field1 = models.CharField('Field 1', max_length=255, blank=True)
    field2 = models.CharField('Field 2', max_length=255, blank=True)
    // ...

def do_something(sender, **kwargs):
    if kwargs.get('created', FALSE):
        video = kwargs['instance']
        video._changed_fields = {} // Manually reset changed-fields.
        video.field2 = 'some value'
        video.save()

post_save.connect(do_something, sender=Video)

// Somewhere else.
def create_video_view():
    video = Video()
    video.field1 = '12345'
    video.save()
```

In the post-save callback, I find that I have to manually reset `_changed_fields` because it still contains fields from the previous save.

If I don't do this, I receive the following error:

```
videos/models.py:76: in do_something
>           video.save()
../.virtualenvs/api/local/lib/python2.7/site-packages/save_the_change/mixins.py:139: in save
>           super(SaveTheChange, self).save(*args, **kwargs)
../.virtualenvs/api/local/lib/python2.7/site-packages/save_the_change/mixins.py:114: in save
>           super(BaseChangeTracker, self).save(*args, **kwargs)
../.virtualenvs/api/local/lib/python2.7/site-packages/django/db/models/base.py:525: in save
>                                % ', '.join(non_model_fields))
E               ValueError: The following fields do not exist in this model or are m2m fields: id
```

I have no idea where the "id" field actually comes from; I'm assuming it's a django-interna used during object creation (?), which is removed at some point but for some reason remains in `_changed_fields`.

Looking at the code of your mixin, `_changed_fields` should actually be reset automatically in `BaseChangeTracker.save()`. Not sure why that's not happening.

We are using Django 1.6 and Python 2.7.

Any ideas why this might be happening, and what to do about it?

**Comment by artscoop** [comment]
No news on the subject ?

**Comment by karanlyons** [comment]
Sorry guys, I’ve still got no idea what’s going on here and a bunch of other stuff has broken in 1.8. If anyone can fix any of the current issues and submit a pull request I’d be very grateful.

**Comment by davidfischer-ch** [comment]
Hi,

This is not a patch but I had the same issue and I implemented a mix-in for removing the primary key from the list of fields to update. But only if the primary key is not changed. Otherwise it will completely pop it. You can review this mix-in and use it if you find it useful.

https://github.com/davidfischer-ch/pytoolbox/blob/master/pytoolbox/django/models/mixins.py#L73

Disclaimer: You will not find any unit-tests covering the Django related modules. It does not means the code is not safe. In fact, most of the mix-ins are used in production and tested (integration tests) through the unit-tests of two projects. By a cloud transcoding platform called CloudNcode and by my family website. Still, I am willing to write Django unit-tests inside my library but not yet had time to do (ok maybe I am a bit lazy).

**Comment by krisnadwipayana07** [comment]
maybe you insert item in 2 table?
